spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/sim_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create # Options: none, update, create, create-drop, validate
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

  # JWT
  jwt:
    secret: dispart_list_disk_select_disk_one_list_volume_detail_volume
    expiration: 86400000 # 24 heures
    refresh-expiration: 604800000 # 7 jours

  # DevTools
  devtools:
    restart:
      enabled: true
    livereload:
      enabled: true

# Configuration du serveur en d√©veloppement
server:
  port: 8082
  servlet:
    context-path: /api